### ISSUE TITLE
"update_policy_configuration" for PolicyClient not allowing "PUT" request

### ISSUE THREAD

**Issue by PearlSantos** [Microsoft/azure-devops-python-api#173]
Trying to call method `get_policy_configurations` from PolicyClient object (API version 4.1). Method returns this error:

```
Traceback (most recent call last):
  File "update_branch_policy_controller.py", line 67, in <module>
    main()
  File "update_branch_policy_controller.py", line 64, in main
    branch_policy_service.update_policy(policy_configuration_data, args.project_id)
  File "/Users/Pearl/Documents/CDAAS_Asia/azuredevopspy/src/services/branch_policy_service.py", line 24, in update_policy
    self.policy_client.update_policy_configuration(policy_configuration, project_name, policy_configuration_id)
  File "/usr/local/lib/python2.7/site-packages/vsts/policy/v4_0/policy_client.py", line 116, in update_policy_configuration
    content=content)
  File "/usr/local/lib/python2.7/site-packages/vsts/vss_client.py", line 96, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "/usr/local/lib/python2.7/site-packages/vsts/vss_client.py", line 64, in _send_request
    self._handle_error(request, response)
  File "/usr/local/lib/python2.7/site-packages/vsts/vss_client.py", line 248, in _handle_error
    raise VstsClientRequestError(wrapped_exception.message)
vsts.exceptions.VstsClientRequestError: The requested resource does not support http method 'PUT'.
```

However, [Microsoft documentation for Azure DevOps rest API](https://docs.microsoft.com/en-us/rest/api/azure/devops/policy/configurations/delete?view=azure-devops-rest-4.1) claims that updating a policy configuration uses the PUT method. What can be done?

**Comment by PearlSantos** [comment]
@tedchamb , checked the id that was being thrown into the method and it turns out it was null. Thanks so much for the tip!
