### ISSUE TITLE
Maximum number of results incorrect when get_test_results called with `details_to_include`

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-api#187]
Hi,

When called with `details_to_include`, the function `get_test_results` in `test_client.py` returns the following error:

```python
>>> res = test_client.get_test_results(project, 144878, details_to_include="WorkItems")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python37-32\lib\site-packages\vsts\test\v4_1\test_client.py", line 1222, in get_test_results
    route_values=route_values,
  File "c:\python37-32\lib\site-packages\vsts\vss_client.py", line 96, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "c:\python37-32\lib\site-packages\vsts\vss_client.py", line 64, in _send_request
    self._handle_error(request, response)
  File "c:\python37-32\lib\site-packages\vsts\vss_client.py", line 239, in _handle_error
    raise VstsServiceError(wrapped_exception)
vsts.exceptions.VstsServiceError: Maximum 100 test results can be processed in a single call.

Maximum 100 test results can be processed in a single call.
```

This is because there is a conflict with the description of `top` parameter:
```python
:param int top: Number of results to return. Max is 1000 when detailsToInclude is None and 100 otherwise.
```

A simple fix could be to set `top` to 100 when `details_to_include` is not `None`:
```python
if details_to_include is not None:
    top = top or 100
    query_parameters['detailsToInclude'] = self._serialize.query('details_to_include', details_to_include, 'str')
```

A simple workaround is to call the function with the correct numbers of `top` results (not bigger than 100):
```python
>>> res = test_client.get_test_results(project, 144878, details_to_include="WorkItems", top=100)
```

FYI: I use version 4.1 of the API

**Comment by tedchamb** [comment]
@jfthuong , thanks for reporting this.  This code is auto generated, and the code generator has know way of knowing the limitations of the `top` parameter value.
