### ISSUE TITLE
DeserializationError thrown in Update user entitlements response for invalid license type

### ISSUE THREAD

**Issue by ishitam8** [microsoft/azure-devops-python-api#195]
msrest.exceptions.DeserializationError is thrown in **update_user_entitlements and update_user_entitlement** methods for invalid **accountLicenseType** property.
 API response seems to be correct.
Following is stack trace thrown in **update_user_entitlements** method for invalid license type [for example 'none']

Unable to deserialize to object: type, KeyError: ' key: int; value: str '
Traceback (most recent call last):
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1494, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1494, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1449, in deserialize_data
    obj_type = self.dependencies[data_type]
KeyError: ' key: int; value: str '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in execute
    raise ex
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 388, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 378, in _run_job
    cmd_copy.exception_handler(ex)
  File "d:\vsts\cli\devops_ext\2802\azure-devops-cli-extension\azure-devops\azext_devops\dev\common\exception_handler.py", line 22, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 357, in _run_job
    result = cmd_copy(params)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\commands\__init__.py", line 171, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\cli\core\__init__.py", line 442, in default_command_handler
    return op(**command_args)
  File "d:\vsts\cli\devops_ext\2802\azure-devops-cli-extension\azure-devops\azext_devops\dev\team\user.py", line 72, in update_user_entitlement
    user_entitlement_update = client.update_user_entitlement(document=patch_document, user_id=user)
  File "d:\vsts\cli\devops_ext\2802\azure-devops-cli-extension\azure-devops\azext_devops\vstscompressed\member_entitlement_management\v4_1\member_entitlement_management_client.py", line 274, in update_user_entitlement
    return self._deserialize('UserEntitlementsPatchResponse', response)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1228, in __call__
    return self._deserialize(target_obj, data)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1460, in deserialize_data
    return self._deserialize(obj_type, data)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1298, in _deserialize
    raise_with_traceback(DeserializationError, msg, err)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\exceptions.py", line 51, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1294, in _deserialize
    value = self.deserialize_data(raw_value, attr_desc['type'])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in deserialize_iter
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1478, in <listcomp>
    return [self.deserialize_data(a, iter_type) for a in attr]
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1447, in deserialize_data
    return self.deserialize_type[iter_type](data, data_type[1:-1])
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1494, in deserialize_dict
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1494, in <dictcomp>
    return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
  File "C:\Users\ishitam\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\serialization.py", line 1449, in deserialize_data
    obj_type = self.dependencies[data_type]
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: ' key: int; value: str '

**Comment by tedchamb** [comment]
@ishitam8 , can you provide more detail?  accountLicenseType is an object in the sdk, so it should except any value.

**Comment by tedchamb** [comment]
@ishitam8 , I am going to close this issue for now, since I do not have a repro.  If you can provide more details, I will reopen the issue and investigate.
