### ISSUE TITLE
pip search with Artifact feed URL returns 405 HTTP code

### ISSUE THREAD

**Issue by ssoto** [microsoft/azure-devops-python-api#214]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Question, and maybe a bug
*Type*: 
405 Method not allowed when using pip search with feed url parameter  

## Environment
- Server - Azure Artifacts with python pacakge

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I am trying to check if a custom version of a packaged uploaded to feed is available.
To do it, i'm using pip:

    pip search --index "https://MY_USER:VERY_LARGE_HASK_PASSWORD@MY_COMPANY.pkgs.visualstudio.com/_packaging/MY_FEED/pypi/simple/" "test-package-name"
    ERROR: HTTP error 405 while getting URL_WITH_PASSWORD_AND_FEED
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/soto/.virtualenvs/artifacts/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
        status = self.run(options, args)
      File "/home/soto/.virtualenvs/artifacts/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 48, in run
        pypi_hits = self.search(query, options)
      File "/home/soto/.virtualenvs/artifacts/lib/python3.7/site-packages/pip/_internal/commands/search.py", line 65, in search
        hits = pypi.search({'name': query, 'summary': query}, 'or')
      File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
        verbose=self.__verbose
      File "/home/soto/.virtualenvs/artifacts/lib/python3.7/site-packages/pip/_internal/download.py", line 832, in request
        response.raise_for_status()
      File "/home/soto/.virtualenvs/artifacts/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    pip._vendor.requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://MY_COMPANY.pkgs.visualstudio.com/_packaging/MY_FEED/pypi/simple/

Can anyone help me?

**Comment by tedchamb** [comment]
This repo is specific to the python sdk.  Please submit your question on the [Developer Community site](https://developercommunity.visualstudio.com/spaces/21/index.html), so it can get routed to the correct team.
