### ISSUE TITLE
Why is the example of the example unavailable

### ISSUE THREAD

**Issue by Linuxlovers** [microsoft/azure-devops-python-api#256]
i want use api  to get a item
but i cant/t

#!/usr/bin/env python
# -*- coding:utf-8 -*- 
__author__ = 'bigc'
# @Time    : 2019/8/6 10:01
# @Email   : bigc@canway.net
from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication
import pprint

# Fill in with your personal access token and org URL
# personal_access_token = 'YOURPAT'
personal_access_token = '<redacted>'
# organization_url = 'https://dev.azure.com/YOURORG'
# organization_url = 'http://tfs.piccnet.com.cn:8080/tfs/PICCCollection/%E7%A4%BE%E4%BF%9D%E4%B8%9A%E5%8A%A1%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F'
# organization_url = 'http://10.10.0.102:8080/tfs/'
organization_url = 'http://tfs.piccnet.com.cn:8080/tfs/PICCCollection/%E9%9B%86%E4%B8%AD%E6%8A%A5%E6%A1%88%E7%B3%BB%E7%BB%9F/_versionControl?path=%24%2F%E9%9B%86%E4%B8%AD%E6%8A%A5%E6%A1%88%E7%B3%BB%E7%BB%9F%2FMain%2Fserver%2Fjars%2FV1.0.0.0'
# PICCAD\xiachengcheng01
# Sop349761
# Create a connection to the org
credentials = BasicAuthentication('', personal_access_token)
# credentials = BasicAuthentication('71000367', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

# Get a client (the "core" client provides access to projects, teams, etc)
core_client = connection.clients.get_core_client()

# Get the list of projects in the org
projects = core_client.get_projects()

# Show details about each project in the console
for project in projects:
    pprint.pprint(project.__dict__)

-----------------------------------------------------
response

Traceback (most recent call last):
  File "F:/projects/day078/try_get_pakge.py", line 25, in <module>
    core_client = connection.clients.get_core_client()
  File "E:\Envs\picc\lib\site-packages\azure\devops\released\client_factory.py", line 44, in get_core_client
    return self._connection.get_client('azure.devops.released.core.core_client.CoreClient')
  File "E:\Envs\picc\lib\site-packages\azure\devops\connection.py", line 45, in get_client
    self._client_cache[client_type] = self._get_client_instance(client_class)
  File "E:\Envs\picc\lib\site-packages\azure\devops\connection.py", line 58, in _get_client_instance
    url = self._get_url_for_client_instance(client_class)
  File "E:\Envs\picc\lib\site-packages\azure\devops\connection.py", line 70, in _get_url_for_client_instance
    resource_areas = self._get_resource_areas()
  File "E:\Envs\picc\lib\site-packages\azure\devops\connection.py", line 119, in _get_resource_areas
    self._resource_areas = location_client.get_resource_areas()
  File "E:\Envs\picc\lib\site-packages\azure\devops\v5_0\location\location_client.py", line 107, in get_resource_areas
    query_parameters=query_parameters)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 77, in _send
    query_parameters=query_parameters)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 119, in _create_request_message
    location = self._get_resource_location(location_id)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 148, in _get_resource_location
    Client._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 184, in _get_resource_locations
    response = self._send_request(request, headers=headers)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "E:\Envs\picc\lib\site-packages\azure\devops\client.py", line 246, in _handle_error
    raise AzureDevOpsServiceError(wrapped_exception)
azure.devops.exceptions.AzureDevOpsServiceError

Process finished with exit code 1

**Comment by tedchamb** [comment]
I am not sure I understand the question?  Are you saying the example code is not working for you?  If that is the case ensure your PAT has the correct scopes.  Creating a temporary PAT with all scopes enabled is a good way to do a quick test.  

Add the following code to enable more logging, and send the response after scrubbing for sensitive data:
```
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by tedchamb** [comment]
@Linuxlovers I am going to close this for now.  I will reopen once you send more info.
