### ISSUE TITLE
code fails in some environments

### ISSUE THREAD

**Issue by rifaterdemsahin** [microsoft/azure-devops-python-api#263]
Code that fails in some python 2.7 environments

definitions = releaseclient.get_release_definitions(project,search_text=None)
for mypipeline in definitions:
   print("can not reach here")

Reddit Thread on it.
https://www.reddit.com/r/learnpython/comments/cq7pdq/getting_iteration_errors_while_converting_code/

**Comment by tedchamb** [comment]
What version are you using?  There is a breaking change in the latest version which was made to support access to the continuation token.  For the latest version you will need to change it to something like this:

```
definitions = releaseclient.get_release_definitions(project,search_text=None)
for mypipeline in definitions.value:
    ...
```

Here is an example of how to use the Continuation Token:
```
# Get the first page of projects
get_projects_response = core_client.get_projects()
index = 0
while get_projects_response is not None:
    for project in get_projects_response.value:
        pprint.pprint("[" + str(index) + "] " + project.name)
        index += 1
    if get_projects_response.continuation_token is not None and get_projects_response.continuation_token != "":
        # Get the next page of projects
        get_projects_response = core_client.get_projects(continuation_token=get_projects_response.continuation_token)
    else:
        # All projects have been retrieved
        get_projects_response = None
```

**Comment by rifaterdemsahin** [comment]
What version are you using? 

erdem.sahin$ pip freeze
aiohttp==3.5.4
astroid==2.2.5
async-timeout==3.0.1
attrs==19.1.0
azure-devops==5.0.0b9

**Comment by tedchamb** [comment]
Ok its not related to the breaking change as that was introduced in this release: https://github.com/microsoft/azure-devops-python-api/releases/tag/5.1.0b2

Do you have any information about differences between environments that work and those that do not?

**Comment by rifaterdemsahin** [comment]
when I use .value than the other environment which is using the same python 2.7.10 stops working

Error: Error running command 'python './../../modules/xxx/scripts/xxx.py'': exit status 1. Output: 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
Traceback (most recent call last):
  File "./../../modules/xxx/scripts/xxx.py", line 75, in <module>
    for mypipeline in definitions.value:
AttributeError: 'list' object has no attribute 'value'

**Comment by rifaterdemsahin** [comment]
Do you have any information about differences between environments that work and those that do not?

after updating the syntax to .value now the working environment stopped but not working environment is fine.
Here is the not working environment with ".value" syntax

pip2 freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
adal==0.5.0
altgraph==0.10.2
ansible==2.4.3.0
apache-libcloud==0.17.0
asn1crypto==0.24.0
azure==3.0.0
azure-batch==4.0.0
azure-common==1.1.8
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.2
azure-datalake-store==0.0.18
azure-devops==5.0.0b9
azure-eventgrid==0.1.0
azure-graphrbac==0.40.0
azure-keyvault==0.3.7
azure-mgmt==2.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==5.0.0
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==2.0.0
azure-mgmt-cognitiveservices==2.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==0.3.1
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.1
azure-mgmt-cosmosdb==0.3.1
azure-mgmt-datafactory==0.4.0
azure-mgmt-datalake-analytics==0.3.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.3.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==1.2.0
azure-mgmt-hanaonazure==0.1.0
azure-mgmt-iothub==0.4.0
azure-mgmt-iothubprovisioningservices==0.1.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-loganalytics==0.1.0
azure-mgmt-logic==2.1.0
azure-mgmt-machinelearningcompute==0.4.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==0.2.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.1
azure-mgmt-notificationhubs==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-powerbiembedded==1.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.2.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-search==1.0.0
azure-mgmt-servermanager==1.2.0
azure-mgmt-servicebus==0.4.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.5
azure-mgmt-storage==1.5.0
azure-mgmt-subscription==0.1.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.1.2.9
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.1.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.1.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
cryptography==2.1.4
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.19
isodate==0.6.0
Jinja2==2.10
keyring==11.0.0
macholib==1.5.1
MarkupSafe==1.0
matplotlib==1.3.1
modulegraph==0.10.4
msrest==0.6.8
msrestazure==0.4.22
ntlm-auth==1.0.6
numpy==1.8.0rc1
oauthlib==2.0.6
packaging==16.8
paramiko==2.4.0
pathlib2==2.3.0
pprint==0.1
py2app==0.7.3
pyasn1==0.4.2
pycparser==2.18
pycrypto==2.6.1
PyJWT==1.5.3
PyNaCl==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
pywinrm==0.3.0
PyYAML==3.12
requests==2.18.4
requests-ntlm==1.1.0
requests-oauthlib==0.8.0
scandir==1.7
scipy==0.13.0b1
six==1.4.1
typing==3.7.4
urllib3==1.22
vboxapi==1.0
xattr==0.6.4
xmltodict==0.11.0

**Comment by rifaterdemsahin** [comment]
**a working environment with .value syntax** 

pip2 freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
altgraph==0.10.2
azure-devops==5.1.0b3
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2019.3.9
chardet==3.0.4
enum34==1.1.6
idna==2.8
isodate==0.6.0
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
msrest==0.6.9
numpy==1.8.0rc1
oauthlib==3.1.0
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
requests==2.22.0
requests-oauthlib==1.2.0
scipy==0.13.0b1
six==1.4.1
typing==3.7.4
urllib3==1.25.3
vboxapi==1.0
xattr==0.6.4

**Comment by rifaterdemsahin** [comment]
After .value syntax change

Not working enviroment package:  azure-devops==5.0.0b9
working enviroment package: azure-devops==5.1.0b3 ( latest version i suppose )

**Comment by tedchamb** [comment]
Yes, this would be expected.  There is a breaking change between the two versions you have listed above.

**Comment by rifaterdemsahin** [comment]
so if i did not update the library it would have worked but when i update it it is going to bring in the breakind changes.

so would it make sense for me to use azure logic apps and save the version and create an immutable workflow to avoid this issue.

when an update comes in i create a new workflow and use that library for that purposes. and always download the library with the version tag.

**Comment by tedchamb** [comment]
Yes, you would want to lock the version of the sdk you depend on.  When a new version is out, you can then test your code with that version, and make changes if necessary.  Once you know its working then you can change your dependency to the latest version.  At this point breaking changes are rare.  I hope to have a release version soon, at which point, there should be no more breaking changes between patch versions.

**Comment by michaelschon** [comment]
$ python3 devops.py 
Traceback (most recent call last):
  File "/home/mschon/Scripts/Python/DEVOPS/old3/devops.py", line 21, in <module>
    for project in get_projects_response.value:
AttributeError: 'list' object has no attribute 'value'
