### ISSUE TITLE
Variable Groups authentication error when using PAT

### ISSUE THREAD

**Issue by TheLonelyGhost** [microsoft/azure-devops-python-api#347]
There appears to be an issue with how the SDK is communicating with the back-end API for Azure DevOps. See below for replication case and relevant system information.

------

**OS:** MacOS 10.15.6

```
➜ tmp % python3 --version
Python 3.8.0
➜ tmp % pip install mypy flake8 azure-devops==5.1.0b7
Collecting mypy
  Using cached mypy-0.782-cp38-cp38-macosx_10_9_x86_64.whl (8.8 MB)
Collecting flake8
  Using cached flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting azure-devops==5.1.0b7
  Using cached azure_devops-5.1.0b7-py3-none-any.whl (1.3 MB)
Collecting typed-ast<1.5.0,>=1.4.0
  Using cached typed_ast-1.4.1-cp38-cp38-macosx_10_15_x86_64.whl (224 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting msrest<0.7.0,>=0.6.0
  Using cached msrest-0.6.17-py2.py3-none-any.whl (84 kB)
Collecting requests-oauthlib>=0.5.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting requests~=2.16
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting isodate>=0.6.0
  Using cached isodate-0.6.0-py2.py3-none-any.whl (45 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: typed-ast, mypy-extensions, typing-extensions, mypy, pyflakes, mccabe, pycodestyle, flake8, chardet, certifi, idna, urllib3, requests, oauthlib, requests-oauthlib, six, isodate, msrest, azure-devops
Successfully installed azure-devops-5.1.0b7 certifi-2020.6.20 chardet-3.0.4 flake8-3.8.3 idna-2.10 isodate-0.6.0 mccabe-0.6.1 msrest-0.6.17 mypy-0.782 mypy-extensions-0.4.3 oauthlib-3.1.0 pycodestyle-2.6.0 pyflakes-2.2.0 requests-2.24.0 requests-oauthlib-1.3.0 six-1.15.0 typed-ast-1.4.1 typing-extensions-3.7.4.2 urllib3-1.25.10
➜ tmp % pip freeze
azure-devops==5.1.0b7
certifi==2020.6.20
chardet==3.0.4
flake8==3.8.3
idna==2.10
isodate==0.6.0
mccabe==0.6.1
msrest==0.6.17
mypy==0.782
mypy-extensions==0.4.3
oauthlib==3.1.0
pycodestyle==2.6.0
pyflakes==2.2.0
requests==2.24.0
requests-oauthlib==1.3.0
six==1.15.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.10
➜ tmp %
```

Sample script to reproduce:

```python
#!/usr/bin/env python3

import os
from pprint import pprint

from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication


ADO_PERSONAL_ACCESS_TOKEN = os.environ['ADO_PERSONAL_ACCESS_TOKEN']
ADO_PROJECT = os.environ['ADO_PROJECT']
ADO_ORGANIZATION = os.environ['ADO_ORGANIZATION']


def main():
    base = Connection(base_url='https://dev.azure.com/{}'.format(ADO_ORGANIZATION), creds=BasicAuthentication('', ADO_PERSONAL_ACCESS_TOKEN))
    task_agent = base.get_client('azure.devops.v5_1.task_agent.task_agent_client.TaskAgentClient')
    service_endpoint = base.get_client('azure.devops.v5_1.service_endpoint.service_endpoint_client.ServiceEndpointClient')

    # Prove that it's a working personal access token:
    services = service_endpoint.get_service_endpoints(project=ADO_PROJECT)
    pprint(services)
    # Replicate the bug:
    groups = task_agent.get_variable_groups(project=ADO_PROJECT)
    pprint(groups)


if __name__ == '__main__':
    main()
```

Here's the output for the above script (given my PS1 is `{exit-code} ➜ {cwd} %`)

```
➜ tmp % ./bug_replication.py
[<azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110cc6eb0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110cc6fd0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90130>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90250>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90370>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90490>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c905b0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c906d0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c907f0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90910>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90a30>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90b50>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90c70>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90d90>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90eb0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110c90fd0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66130>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66250>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66370>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66490>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d665b0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d666d0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d667f0>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66910>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66a30>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66b50>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66c70>,
 <azure.devops.v5_1.service_endpoint.models.ServiceEndpoint object at 0x110d66d90>]
Traceback (most recent call last):
  File "./bug_replication.py", line 28, in <module>
    main()
  File "./bug_replication.py", line 23, in main
    groups = task_agent.get_variable_groups(project=ADO_PROJECT)
  File "/Users/me/workspace/github.com/thelonelyghost/tmp/.direnv/python-3.8.0/lib/python3.8/site-packages/azure/devops/v5_1/task_agent/task_agent_client.py", line 937, in get_variable_groups
    response = self._send(http_method='GET',
  File "/Users/me/workspace/github.com/thelonelyghost/tmp/.direnv/python-3.8.0/lib/python3.8/site-packages/azure/devops/client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/Users/me/workspace/github.com/thelonelyghost/tmp/.direnv/python-3.8.0/lib/python3.8/site-packages/azure/devops/client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "/Users/me/workspace/github.com/thelonelyghost/tmp/.direnv/python-3.8.0/lib/python3.8/site-packages/azure/devops/client.py", line 290, in _handle_error
    raise AzureDevOpsAuthenticationError(full_message_format.format(error_message=error_message,
azure.devops.exceptions.AzureDevOpsAuthenticationError: The requested resource requires user authentication: https://karauctionservices.visualstudio.com/openlane/_apis/distributedtask/variablegroups
1 ➜ tmp %
```

**Comment by TheLonelyGhost** [comment]
I have a timeline! Given I have this in a CI pipeline and have replicated to the exact same versions of the library as the CI pipeline has, the problem was introduced between 4am EDT and 11:30am EDT today.

**Comment by tedchamb** [comment]
@TheLonelyGhost , i was able to run your code without any issues.  Make sure you have the proper scopes enabled on your PAT, and that you have access to the resource.
