### ISSUE TITLE
Errors when convert py to exe

### ISSUE THREAD

**Issue by Gerphan94** [microsoft/azure-devops-python-api#410]
Hi, 
When i run code on py, it working
But when i convert to exe (use "auto-py-to-exe"), errors:
--
Traceback (most recent call last):
  File "Azure_v3.py", line 24, in <module>
    wit_client = cnt.clients.get_work_item_tracking_client()
  File "azure\devops\released\client_factory.py", line 170, in get_work_item_tracking_client
  File "azure\devops\connection.py", line 44, in get_client
  File "azure\devops\connection.py", line 52, in _get_class
ModuleNotFoundError: No module named 'azure.devops.released.work_item_tracking'
![whenconverttoexe](https://user-images.githubusercontent.com/81787710/162662229-1327c14c-3f08-45ef-9acb-85ec14bc78f2.jpg)

**Comment by TeaKnight42** [comment]
Same here:
![image](https://github.com/microsoft/azure-devops-python-api/assets/101829084/31819401-55a5-4758-a7b9-dd173c08a81a)
azure-devops              7.1.0b4

**Comment by TeaKnight42** [comment]
Fixed manually by import of required library to file:
_import azure.devops.v7_1.work_item_tracking.work_item_tracking_client_ (or 7.0, if u wish).
