### ISSUE TITLE
Can no longer get any client - azure.core.exceptions.DeserializationError

### ISSUE THREAD

**Issue by remyjette** [microsoft/azure-devops-python-api#460]
Beginning today, any attempt to call `get_*_client()` raises a `azure.core.exceptions.DeserializationError`:

```
>>> client = connection.clients.get_git_client()
Traceback (most recent call last):
  File "/home/remyjette/.local/lib/python3.10/site-packages/msrest/pipeline/universal.py", line 170, in deserialize_from_text
    return json.loads(data_as_str)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 163804 (char 163803)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/released/client_factory.py", line 135, in get_git_client
    return self._connection.get_client('azure.devops.v7_0.git.git_client.GitClient')
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 45, in get_client
    self._client_cache[client_type] = self._get_client_instance(client_class)
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 58, in _get_client_instance
    url = self._get_url_for_client_instance(client_class)
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 70, in _get_url_for_client_instance
    resource_areas = self._get_resource_areas()
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 120, in _get_resource_areas
    self._resource_areas = location_client.get_resource_areas()
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/v7_1/location/location_client.py", line 104, in get_resource_areas
    response = self._send(http_method='GET',
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/client.py", line 74, in _send
    request = self._create_request_message(http_method=http_method,
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/client.py", line 119, in _create_request_message
    location = self._get_organization_resource_location(location_id)
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/client.py", line 160, in _get_organization_resource_location
    return self._get_resource_location(self.normalized_url, location_id)
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/client.py", line 172, in _get_resource_location
    Client._locations_cache[url] = self._get_resource_locations(url, all_host_types=False)
  File "/home/remyjette/.local/lib/python3.10/site-packages/azure/devops/client.py", line 209, in _get_resource_locations
    wrapper = self._base_deserialize('VssJsonCollectionWrapper', response)
  File "/home/remyjette/.local/lib/python3.10/site-packages/msrest/serialization.py", line 1375, in __call__
    data = self._unpack_content(response_data, content_type)
  File "/home/remyjette/.local/lib/python3.10/site-packages/msrest/serialization.py", line 1554, in _unpack_content
    return RawDeserializer.deserialize_from_http_generics(
  File "/home/remyjette/.local/lib/python3.10/site-packages/msrest/pipeline/universal.py", line 226, in deserialize_from_http_generics
    return cls.deserialize_from_text(body_bytes, content_type)
  File "/home/remyjette/.local/lib/python3.10/site-packages/msrest/pipeline/universal.py", line 172, in deserialize_from_text
    raise DeserializationError("JSON is invalid: {}".format(err), err)
azure.core.exceptions.DeserializationError: ('JSON is invalid: Unterminated string starting at: line 1 column 163804 (char 163803)', JSONDecodeError('Unterminated string starting at: line 1 column 163804 (char 163803)'))
```

**Comment by nechvatalp** [comment]
@remyjette Hello, were you using the latest version? Could you test older version if it exhibits the same issue?

Unfortunately, I am unable to reproduce the issue.

**Comment by remyjette** [comment]
My project is currently using 6.0.0b4 and clients_v5_1 and hit this issue.

I tried upgrading to 7.1.0b3 and just using connection.clients and still hit the same issue.

**Comment by remyjette** [comment]
This issue was caused by requests 2.30.0, which has been yanked:

'requests' candidate (version 2.30.0 at https://files.pythonhosted.org/packages/96/80/034ffeca15c0f4e01b7b9c6ad0fb704b44e190cde4e757edbd60be404c41/requests-2.30.0-py3-none-any.whl (from https://pypi.org/simple/requests/) (requires-python:>=3.7))
Reason for being yanked: Broken responses when reading compressed content through urllib3

So, closing this. Manually switching to 2.29.0 fixed the issue.
