### ISSUE TITLE
GitClient class raises a serialization error when creating a repo

### ISSUE THREAD

**Issue by gparonitti** [Microsoft/azure-devops-python-api#80]
I'm trying to create a repo with the create_repository method in GitClient class. But it raises the following exception. I have tried to follow back the error and it seems to me that it is generated from the `serialization.py` script when it's trying to serialize the body (line 445 and on). Maybe there is some problem in data_type argument (which is passed from git_client_base.py as `content = self._serialize.body(git_repository_to_create, 'GitRepositoryCreateOptions')`) consumed by the body serialization method. This is the transcript of the error:

```
Traceback (most recent call last):
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1020, in __call__
    found_value = key_extractor(attr, attr_desc, data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 907, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 930, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 470, in body
    data = deserializer(data_type, data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1030, in __call__
    raise_with_traceback(DeserializationError, msg, err)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1020, in __call__
    found_value = key_extractor(attr, attr_desc, data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 907, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 930, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 71, in <module>
    main()
  File "src/__main__.py", line 67, in main
    _res_repo_creation = vsts.create_git_repo(repo_name)
  File "src/lib/vsts.py", line 25, in create_git_repo
    return self.git_client.create_repository(repo_name, self.project_id)
  File "[omitted]/venv/lib/python3.6/site-packages/vsts/git/v4_1/git_client_base.py", line 2761, in create_repository
    content = self._serialize.body(git_repository_to_create, 'GitRepositoryCreateOptions')
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 473, in body
    SerializationError, "Unable to build a model: "+str(err), err)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 470, in body
    data = deserializer(data_type, data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1030, in __call__
    raise_with_traceback(DeserializationError, msg, err)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 1020, in __call__
    found_value = key_extractor(attr, attr_desc, data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 907, in rest_key_case_insensitive_extractor
    return attribute_key_case_insensitive_extractor(key, None, working_data)
  File "[omitted]/venv/lib/python3.6/site-packages/msrest/serialization.py", line 930, in attribute_key_case_insensitive_extractor
    return data.get(found_key)
msrest.exceptions.SerializationError: Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
```

**Comment by tedchamb** [comment]
@gparonitti Is there any chance you are setting the value of the `project` property on `GitRepositoryCreateOptions` to the project name (str) instead of a `git.v4_1.models.TeamProjectReference`?

**Comment by gparonitti** [comment]
Hi this is my class (vstsmanager.py): 
```
from vsts.vss_connection import VssConnection
from msrest.authentication import BasicAuthentication
import pprint


class Vsts:
    def __init__(self, token, team_instance, project_id):
        self.token = token
        self.team_instance = team_instance
        self.project_id = project_id

        credentials = BasicAuthentication('', self.token)
        connection = VssConnection(base_url=self.team_instance, creds=credentials)

        self.core_client = connection.get_client('vsts.core.v4_0.core_client.CoreClient')
        self.git_client = connection.get_client('vsts.git.v4_1.git_client.GitClient')

    def get_team_projects(self):
        return self.core_client.get_projects()

    def print_project(self):
        for project in self.get_team_projects():
            pprint.pprint(project.__dict__)

    def create_git_repo(self, repo_name):
        return self.git_client.create_repository(git_repository_to_create=repo_name, project=self.project_id)
```
And this is how I implement it:
```
config = env.get_config()
vsts = Vsts(config.VSTS_ACCESS_TOKEN, config.TEAM_INSTANCE, config.PROJECT_ID)
...
_res_repo_creation = vsts.create_git_repo(repo_name)
logger.info(_res_repo_creation)
```

Maybe I didn't pass the arguments correctly? Now that you have pointed me to the model I'll try with it in the body. And let you know.

**Comment by gparonitti** [comment]
Yes it was my fault! I passed a string instead of an instance of the model. 
Could you please point me to any kind of documentation? It becomes a long process (paved with errors) if I have to go through your module code for understanding all the APIs that are needed. Thank you very much!

**Comment by tedchamb** [comment]
@gparonitti I will look into catching this error and raising a better error message.

The python api is a thin wrapper around our REST end points.  You can find details for each end point at the following site:
https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-4.1
